ARG TEMPLATE_IMAGE

ARG DEVTOOLS_IMAGE
ENV DEVTOOLS_IMAGE=${DEVTOOLS_IMAGE:-lenra/devtools}

FROM ${DEVTOOLS_IMAGE} as devtools

FROM ${TEMPLATE_IMAGE}

ENV fprocess=$fprocess_debug

COPY --from=devtools /lenra/devtools /lenra/devtools

USER root
# Install elixir dependencies
RUN apk add --no-cache ncurses-libs libstdc++

USER app

VOLUME [ "/home/app/application" ]
ENTRYPOINT [ "/lenra/devtools/entrypoint.sh" ]
CMD ["fwatchdog"]
