ARG TEMPLATE_IMAGE

ARG DEVTOOLS_IMAGE

FROM lenra/devtools:${DEVTOOLS_IMAGE:-1.0.0-beta.26} as devtools

FROM ${TEMPLATE_IMAGE}

ENV fprocess=$fprocess_debug

COPY --from=devtools /lenra/devtools /lenra/devtools

USER root
# Install elixir dependencies
RUN apk add --no-cache ncurses-libs libstdc++

USER app

VOLUME [ "/home/app/application" ]
ENTRYPOINT [ "/lenra/devtools/entrypoint.sh" ]
CMD ["fwatchdog"]
